test:
  appearance:
    no-color: false
    show-packages-with-no-tests: false

profiles:
  unit:
    test:
      cover: true
      covermin: 55
      packages:
        - ./...
      exclude:
        - '**/internal/test-fixtures/**'
