package cover

// Note: this is a modified copy from https://github.com/golang/go/blob/master/src/cmd/cover/func.go

// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file implements the visitor that computes the (line, column)-(line-column) range for each function.

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"os/exec"
	"path"
	"path/filepath"
	"strings"

	"golang.org/x/tools/cover"
)

// CoverageProfile parses a Go coverage profile file and calculates the overall coverage percentage.
// It reads the profile, resolves package locations, and aggregates coverage across all functions.
// The profile parameter should be a path to a coverage profile generated by go test -coverprofile.
// Returns the coverage percentage (0-100), parsed profiles for structured storage, and any error.
//
// Example output format that this function processes:
//
//	fmt/format.go:30:	init			100.0%
//	fmt/format.go:57:	clearflags		100.0%
//	...
//	fmt/scan.go:1046:	doScan			100.0%
//	fmt/scan.go:1075:	advance			96.2%
//	fmt/scan.go:1119:	doScanf			96.8%
//	total:		(statements)			91.9%
func CoverageProfile(profile string) (float64, []*cover.Profile, error) {
	profiles, err := cover.ParseProfiles(profile)
	if err != nil {
		return -1, nil, err
	}

	dirs, err := findPkgs(profiles)
	if err != nil {
		return -1, nil, err
	}

	var total, covered int64
	for _, profile := range profiles {
		fn := profile.FileName
		file, err := findFile(dirs, fn)
		if err != nil {
			return -1, nil, err
		}
		funcs, err := findFuncs(file)
		if err != nil {
			return -1, nil, err
		}
		// match up functions and profile blocks
		for _, f := range funcs {
			c, t := f.coverage(profile)
			total += t
			covered += c
		}
	}

	return percent(covered, total), profiles, nil
}

// findFuncs parses a Go source file and extracts function extent information.
// Returns a slice of FuncExtent descriptors containing line and column positions for each function.
func findFuncs(name string) ([]*FuncExtent, error) {
	fset := token.NewFileSet()
	parsedFile, err := parser.ParseFile(fset, name, nil, 0)
	if err != nil {
		return nil, err
	}
	visitor := &FuncVisitor{
		fset:    fset,
		name:    name,
		astFile: parsedFile,
	}
	ast.Walk(visitor, visitor.astFile)
	return visitor.funcs, nil
}

// FuncExtent describes a function's extent in the source code by file position.
// It tracks the start and end line/column for matching against coverage profile blocks.
type FuncExtent struct {
	name      string
	startLine int
	startCol  int
	endLine   int
	endCol    int
}

// FuncVisitor implements the ast.Visitor interface to build a list of function positions.
// It walks the AST to find function declarations and record their extents.
type FuncVisitor struct {
	// fset is the file set used for position information.
	fset *token.FileSet

	// name is the source file name being visited.
	name string

	// astFile is the parsed AST of the source file.
	astFile *ast.File

	// funcs contains all discovered function extents.
	funcs []*FuncExtent
}

// Visit implements the ast.Visitor interface for traversing the AST.
// It collects function declarations and their position extents.
func (v *FuncVisitor) Visit(node ast.Node) ast.Visitor {
	switch n := node.(type) {
	case *ast.FuncDecl:
		if n.Body == nil {
			// Do not count declarations of assembly functions.
			break
		}
		start := v.fset.Position(n.Pos())
		end := v.fset.Position(n.End())
		fe := &FuncExtent{
			name:      n.Name.Name,
			startLine: start.Line,
			startCol:  start.Column,
			endLine:   end.Line,
			endCol:    end.Column,
		}
		v.funcs = append(v.funcs, fe)
	}
	return v
}

// coverage calculates the number of covered and total statements for this function.
// It matches coverage profile blocks against the function's source extent.
// Returns covered statements and total statements as separate int64 values.
func (f *FuncExtent) coverage(profile *cover.Profile) (num, den int64) {
	// We could avoid making this n^2 overall by doing a single scan and annotating the functions,
	// but the sizes of the data structures is never very large and the scan is almost instantaneous.
	var covered, total int64
	// The blocks are sorted, so we can stop counting as soon as we reach the end of the relevant block.
	for _, b := range profile.Blocks {
		if b.StartLine > f.endLine || (b.StartLine == f.endLine && b.StartCol >= f.endCol) {
			// Past the end of the function.
			break
		}
		if b.EndLine < f.startLine || (b.EndLine == f.startLine && b.EndCol <= f.startCol) {
			// Before the beginning of the function
			continue
		}
		total += int64(b.NumStmt)
		if b.Count > 0 {
			covered += int64(b.NumStmt)
		}
	}
	return covered, total
}

// Pkg describes a single Go package, compatible with JSON output from 'go list'.
// This structure matches the format documented in 'go help list'.
type Pkg struct {
	// ImportPath is the package import path.
	ImportPath string

	// Dir is the filesystem directory containing the package source.
	Dir string

	// Error contains any error that occurred while loading the package.
	Error *struct {
		Err string
	}
}

// findPkgs resolves package directories for all packages referenced in coverage profiles.
// It runs 'go list' to determine filesystem locations for package import paths.
func findPkgs(profiles []*cover.Profile) (map[string]*Pkg, error) {
	// Run go list to find the location of every package we care about.
	pkgs := make(map[string]*Pkg)
	var list []string
	for _, profile := range profiles {
		if strings.HasPrefix(profile.FileName, ".") || filepath.IsAbs(profile.FileName) {
			// Relative or absolute path.
			continue
		}
		pkg := path.Dir(profile.FileName)
		if _, ok := pkgs[pkg]; !ok {
			pkgs[pkg] = nil
			list = append(list, pkg)
		}
	}

	if len(list) == 0 {
		return pkgs, nil
	}

	goTool, err := exec.LookPath("go")
	if err != nil {
		return nil, fmt.Errorf("cannot find go tool: %w", err)
	}
	cmd := exec.Command(goTool, append([]string{"list", "-e", "-json"}, list...)...)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	stdout, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("cannot run go list: %v\n%s", err, stderr.Bytes())
	}
	dec := json.NewDecoder(bytes.NewReader(stdout))
	for {
		var pkg Pkg
		err := dec.Decode(&pkg)
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("decoding go list json: %v", err)
		}
		pkgs[pkg.ImportPath] = &pkg
	}
	return pkgs, nil
}

// findFile resolves the filesystem path for a coverage profile file.
// It handles relative paths, absolute paths, and package-based paths using the package directory map.
func findFile(pkgs map[string]*Pkg, file string) (string, error) {
	if strings.HasPrefix(file, ".") || filepath.IsAbs(file) {
		// Relative or absolute path.
		return file, nil
	}
	pkg := pkgs[path.Dir(file)]
	if pkg != nil {
		if pkg.Dir != "" {
			return filepath.Join(pkg.Dir, path.Base(file)), nil
		}
		if pkg.Error != nil {
			return "", errors.New(pkg.Error.Err)
		}
	}
	return "", fmt.Errorf("did not find package for %s in go list output", file)
}

// percent calculates coverage percentage from covered and total statement counts.
// It avoids division by zero by treating zero total as 1.
func percent(covered, total int64) float64 {
	if total == 0 {
		total = 1 // Avoid zero denominator.
	}
	return 100.0 * float64(covered) / float64(total)
}
